version: "3.7"

x-templates:
    backend: &backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        networks:
            - crawler_network
services:
    app:
        <<: *backend
        container_name: app
        ports:
            - "3000:3000"
        volumes:
            - ./database.sqlite:/app/database.sqlite:ro
        depends_on:
            - crawler
            - redis
        command: node index.js
    crawler:
        <<: *backend
        container_name: crawler
        expose:
            - "3001"
        volumes:
            - ./database.sqlite:/app/database.sqlite:rw
        depends_on:
            - redis
        command: node /app/src/queue/worker.js
    redis:
        image: redis:latest
        container_name: crawler_redis
        restart: always
        expose:
            - "6379"
        volumes:
            - redis_data:/data
        networks:
            - crawler_network
networks:
    crawler_network:
        driver: bridge
volumes:
    redis_data:
        driver: local
