version: "3.7"
services:
    redis:
        image: redis:latest
        container_name: crawler_redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
volumes:
    redis_data:
        driver: local
